### ISSUE TITLE
Hard-coded layer for scintillator fine vs coarse granularity

### ISSUE THREAD

**Issue by amagnan** [pfs/PFCal#33]
this line has an hardcoded 57 which needs to be changed !! Sorry !
https://github.com/pfs/PFCal/blob/e87267c83b260e904857843e12ddb0c575076e61/PFCalEE/src/EventAction.cc#L172

@pfs I don't have a quick nice solution at hand... maybe passing it through the samplesection class when constructing the geometry - or, because it would have to be hardcoded anyway somewhere, we make a flag here "if version== v8, the57 = 57 else if ... but we'd have to remember to set this correctly in this class when it changes..... Any better idea ?

**Comment by pfs** [comment]
nice catch - i completely forgot that
In the branch i had 2yr ago for the FH granularity i had in fact created a variable because of this
https://github.com/pfs/PFCal/blob/FHGranularity-v2/PFCalEE/src/EventAction.cc#L177
maybe we can do similar?

**Comment by amagnan** [comment]
Yes I was doing exactly that now !
And same there is a little "28" for the supportCone :P

**Comment by amagnan** [comment]
So I am adding also a counter for the EE layers...

**Comment by amagnan** [comment]
Fixed with incoming MR...
